---
- name: "Configuration | Create config directory for overriding default systemd service"
  ansible.builtin.file:
    path: /etc/systemd/system/gitlab-runner.service.d
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: "Configuration | Override service stop behavior"
  ansible.builtin.template:
    src: etc/systemd/system/gitlab-runner.service.d/kill.conf.j2
    dest: /etc/systemd/system/gitlab-runner.service.d/kill.conf
    owner: root
    group: root
    mode: "0644"
  notify: Reload systemd
