---
# handlers file for ansible-role-gitlab-runner
- name: Restart gitlab-runner service
  ansible.builtin.service:
    name: gitlab-runner
    state: restarted

- name: Reload systemd
  ansible.builtin.systemd:
    name: gitlab-runner
    daemon_reload: true
